server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rendezvous_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

google:
  calendar:
    application-name: RendezVousApp
    credentials-file: credentials.json
